[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pywhatkit>=5.4",
    "requests>=2.32.3",
    "textblob>=0.19.0",
]
